"use client";

import { ConsentFormSchema, ResearchConsentFormSchema } from "@/lib/schema";

const CONSENT_TYPE_LABELS: Record<string, string> = {
  surgical: "SURGICAL",
  anaesthesia: "ANAESTHESIA",
  diagnostic: "DIAGNOSTIC",
  blood_transfusion: "BLOOD TRANSFUSION",
  research: "RESEARCH",
  telemedicine: "TELEMEDICINE",
  minor_procedure: "MINOR PROCEDURE",
  obstetric: "OBSTETRIC",
  psychiatric: "PSYCHIATRIC",
  road_accident_emergency: "ROAD ACCIDENT / EMERGENCY",
};

function ShimmerBlock({ label }: { label: string }) {
  return (
    <div className="mb-6">
      <div className="flex items-center gap-2 mb-3">
        <h4 className="text-xs font-bold uppercase tracking-widest text-neutral-500">{label}</h4>
        <span className="text-xs bg-amber-100 text-amber-700 font-semibold px-2 py-0.5 rounded-full">
          Will be generated by AI
        </span>
      </div>
      <div className="rounded-lg bg-neutral-100 p-4 space-y-2.5">
        <div className="h-2.5 bg-neutral-200 rounded-full w-full" />
        <div className="h-2.5 bg-neutral-200 rounded-full w-11/12" />
        <div className="h-2.5 bg-neutral-200 rounded-full w-4/5" />
        <div className="h-2.5 bg-neutral-200 rounded-full w-full" />
        <div className="h-2.5 bg-neutral-200 rounded-full w-3/4" />
      </div>
    </div>
  );
}

function InfoBanner() {
  return (
    <div
      role="note"
      className="mb-6 rounded-xl border border-amber-200 bg-amber-50 px-5 py-4 flex gap-3 items-start"
    >
      <span className="text-amber-500 text-xl leading-none mt-0.5">&#9888;</span>
      <p className="text-sm text-amber-800 leading-relaxed">
        <strong>This preview shows your entered data.</strong> The AI will generate all legal consent
        clauses during generation. Review your details carefully before spending 1 credit.
      </p>
    </div>
  );
}

function SignatureLine({ label }: { label: string }) {
  return (
    <div className="flex flex-col items-center gap-1">
      <div className="w-36 border-b border-neutral-400" />
      <p className="text-xs text-neutral-600 font-medium">{label}</p>
      <p className="text-xs text-neutral-400">Date: ___________</p>
    </div>
  );
}

interface ConsentPreviewProps {
  data: ConsentFormSchema;
}

export function ConsentPreview({ data }: ConsentPreviewProps) {
  const today = new Date().toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });

  const consentTypeLabel =
    CONSENT_TYPE_LABELS[data.clinical?.consentType ?? "surgical"] ?? "SURGICAL";

  const aadhaar = data.patient?.aadhaarLast4
    ? `****\u00A0****\u00A0****\u00A0${data.patient.aadhaarLast4}`
    : "—";

  return (
    <div>
      <InfoBanner />
      <div className="max-w-2xl mx-auto bg-white border border-neutral-200 shadow-md p-8 font-serif text-neutral-900">
        {/* Header */}
        <div className="flex justify-between items-start mb-6 pb-5 border-b border-neutral-200">
          <div>
            <p className="text-lg font-bold leading-tight">
              {data.clinical?.hospitalName || "Hospital Name"}
            </p>
            <p className="text-xs text-neutral-500 mt-1 leading-relaxed max-w-xs">
              {data.clinical?.hospitalAddress || "Hospital Address"}
            </p>
          </div>
          <div className="text-right text-xs text-neutral-500 space-y-0.5">
            <p>Consent ID: <span className="font-semibold text-neutral-700">AUTO-GENERATED</span></p>
            <p>Date: <span className="font-semibold text-neutral-700">{today}</span></p>
          </div>
        </div>

        {/* Title bar */}
        <div className="bg-neutral-100 rounded-md py-2.5 px-4 mb-6 text-center">
          <p className="text-sm font-bold tracking-widest uppercase">
            INFORMED CONSENT FORM &mdash; {consentTypeLabel} PROCEDURE
          </p>
        </div>

        {/* Patient info table */}
        <div className="mb-6">
          <h3 className="text-xs font-bold uppercase tracking-widest text-neutral-500 mb-2">
            Patient Information
          </h3>
          <table className="w-full text-sm border border-neutral-200 rounded-md overflow-hidden">
            <tbody>
              {[
                ["Patient Name", data.patient?.patientName || "—"],
                ["Age / Sex", `${data.patient?.age || "—"} / ${data.patient?.sex || "—"}`],
                ["Hospital OPD/IPD No.", data.patient?.hospitalOpdIpdNo || "—"],
                ["Aadhaar (last 4)", aadhaar],
                ...(data.patient?.insuranceProvider
                  ? [
                      ["Insurance Provider", data.patient.insuranceProvider],
                      ["Insurance Policy No.", data.patient.insurancePolicyNo || "—"],
                    ]
                  : []),
                ...(!data.patient?.patientCompetent && data.patient?.guardianName
                  ? [
                      ["Guardian Name", data.patient.guardianName],
                      ["Guardian Relationship", data.patient.guardianRelationship || "—"],
                    ]
                  : []),
              ].map(([label, value], i) => (
                <tr key={i} className={i % 2 === 0 ? "bg-white" : "bg-neutral-50"}>
                  <td className="py-1.5 px-3 text-xs font-semibold text-neutral-500 w-44 border-r border-neutral-200">
                    {label}
                  </td>
                  <td className="py-1.5 px-3 text-sm">{value}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Clinical info table */}
        <div className="mb-6">
          <h3 className="text-xs font-bold uppercase tracking-widest text-neutral-500 mb-2">
            Clinical Details
          </h3>
          <table className="w-full text-sm border border-neutral-200 rounded-md overflow-hidden">
            <tbody>
              {[
                ["Physician", `${data.clinical?.doctorName || "—"} (Reg. ${data.clinical?.doctorRegistrationNo || "—"})`],
                ["Procedure", data.clinical?.procedureName || "—"],
                ["Scheduled Date", data.clinical?.procedureDate || "—"],
                ["Counseling Language", data.clinical?.counselingLanguage || "—"],
              ].map(([label, value], i) => (
                <tr key={i} className={i % 2 === 0 ? "bg-white" : "bg-neutral-50"}>
                  <td className="py-1.5 px-3 text-xs font-semibold text-neutral-500 w-44 border-r border-neutral-200">
                    {label}
                  </td>
                  <td className="py-1.5 px-3 text-sm">{value}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Specific risks entered by user */}
        {data.clinical?.specificRisks && (
          <div className="mb-6">
            <h4 className="text-xs font-bold uppercase tracking-widest text-neutral-500 mb-2">
              Specific Risks (Entered)
            </h4>
            <div className="rounded-lg border border-neutral-200 bg-neutral-50 p-4 text-sm leading-relaxed whitespace-pre-wrap">
              {data.clinical.specificRisks}
            </div>
          </div>
        )}

        {/* AI placeholder sections */}
        <ShimmerBlock label="Disclosure of Risks & Complications (AI Generated)" />
        <ShimmerBlock label="Treatment Alternatives (AI Generated)" />
        <ShimmerBlock label="Consent Declaration (AI Generated)" />

        {/* Signature block */}
        <div className="mt-8 pt-6 border-t border-neutral-200">
          <div className="flex justify-around flex-wrap gap-6">
            <SignatureLine label="Patient Signature" />
            <SignatureLine label="Doctor / Physician Signature" />
            {data.includeWitnessBlock && <SignatureLine label="Witness Signature" />}
          </div>
        </div>

        {/* Footer */}
        <div className="mt-8 pt-4 border-t border-neutral-100 text-center">
          <p className="text-xs text-neutral-400">
            Generated by ConsentGen &middot; IMC 2002 Compliant &middot; [timestamp to be added on generation]
          </p>
        </div>
      </div>
    </div>
  );
}

interface ResearchConsentPreviewProps {
  data: ResearchConsentFormSchema;
}

export function ResearchConsentPreview({ data }: ResearchConsentPreviewProps) {
  const today = new Date().toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });

  return (
    <div>
      <InfoBanner />
      <div className="max-w-2xl mx-auto bg-white border border-neutral-200 shadow-md p-8 font-serif text-neutral-900">
        {/* Header */}
        <div className="flex justify-between items-start mb-6 pb-5 border-b border-neutral-200">
          <div>
            <p className="text-lg font-bold leading-tight">
              {data.study?.institutionName || "Institution Name"}
            </p>
            <p className="text-xs text-neutral-500 mt-1 leading-relaxed max-w-xs">
              {data.study?.institutionAddress || "Institution Address"}
            </p>
          </div>
          <div className="text-right text-xs text-neutral-500 space-y-0.5">
            <p>Consent ID: <span className="font-semibold text-neutral-700">AUTO-GENERATED</span></p>
            <p>Date: <span className="font-semibold text-neutral-700">{today}</span></p>
          </div>
        </div>

        {/* Title bar */}
        <div className="bg-neutral-100 rounded-md py-2.5 px-4 mb-6 text-center">
          <p className="text-sm font-bold tracking-widest uppercase">
            INFORMED CONSENT FOR RESEARCH PARTICIPATION
          </p>
        </div>

        {/* Study info table */}
        <div className="mb-6">
          <h3 className="text-xs font-bold uppercase tracking-widest text-neutral-500 mb-2">
            Study Information
          </h3>
          <table className="w-full text-sm border border-neutral-200 rounded-md overflow-hidden">
            <tbody>
              {[
                ["Study Title", data.study?.studyTitle || "—"],
                ["Principal Investigator", data.study?.principalInvestigator || "—"],
                ["Department", data.study?.department || "—"],
                ["Contact", data.study?.contactMobile || "—"],
                ["Counseling Language", data.study?.counselingLanguage || "—"],
              ].map(([label, value], i) => (
                <tr key={i} className={i % 2 === 0 ? "bg-white" : "bg-neutral-50"}>
                  <td className="py-1.5 px-3 text-xs font-semibold text-neutral-500 w-44 border-r border-neutral-200">
                    {label}
                  </td>
                  <td className="py-1.5 px-3 text-sm">{value}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Participant info table */}
        <div className="mb-6">
          <h3 className="text-xs font-bold uppercase tracking-widest text-neutral-500 mb-2">
            Participant Information
          </h3>
          <table className="w-full text-sm border border-neutral-200 rounded-md overflow-hidden">
            <tbody>
              {[
                ["Participant Name", data.participant?.participantName || "—"],
                ["Participant ID", data.participant?.participantId || "—"],
                ["Age / Sex", `${data.participant?.age || "—"} / ${data.participant?.sex || "—"}`],
                ...(!data.participant?.isCompetent && data.participant?.guardianName
                  ? [
                      ["Guardian Name", data.participant.guardianName],
                      ["Guardian Relationship", data.participant.guardianRelationship || "—"],
                    ]
                  : []),
              ].map(([label, value], i) => (
                <tr key={i} className={i % 2 === 0 ? "bg-white" : "bg-neutral-50"}>
                  <td className="py-1.5 px-3 text-xs font-semibold text-neutral-500 w-44 border-r border-neutral-200">
                    {label}
                  </td>
                  <td className="py-1.5 px-3 text-sm">{value}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Study purpose entered */}
        {data.study?.studyPurpose && (
          <div className="mb-6">
            <h4 className="text-xs font-bold uppercase tracking-widest text-neutral-500 mb-2">
              Study Purpose (Entered)
            </h4>
            <div className="rounded-lg border border-neutral-200 bg-neutral-50 p-4 text-sm leading-relaxed whitespace-pre-wrap">
              {data.study.studyPurpose}
            </div>
          </div>
        )}

        {/* AI placeholder sections */}
        <ShimmerBlock label="Voluntary Participation & Withdrawal Rights (AI Generated)" />
        <ShimmerBlock label="Confidentiality & Data Protection (AI Generated)" />
        <ShimmerBlock label="Participant Consent Declaration (AI Generated)" />

        {/* Signature block */}
        <div className="mt-8 pt-6 border-t border-neutral-200">
          <div className="flex justify-around flex-wrap gap-6">
            <SignatureLine label="Participant Signature" />
            {data.includeResearcherDeclaration && (
              <SignatureLine label="Researcher / Investigator Signature" />
            )}
            {data.includeWitnessBlock && <SignatureLine label="Witness Signature" />}
          </div>
        </div>

        {/* Footer */}
        <div className="mt-8 pt-4 border-t border-neutral-100 text-center">
          <p className="text-xs text-neutral-400">
            Generated by ConsentGen &middot; ICMR Guidelines Compliant &middot; [timestamp to be added on generation]
          </p>
        </div>
      </div>
    </div>
  );
}
