import {
  Document,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Packer,
  Header,
  Footer,
  PageNumberElement,
  BorderStyle,
  Table,
  TableRow,
  TableCell,
  WidthType,
  TableBorders,
} from "docx";

function parseBoldRuns(text: string): TextRun[] {
  const runs: TextRun[] = [];
  const regex = /\*\*(.*?)\*\*/g;
  let lastIndex = 0;
  let match: RegExpExecArray | null;

  while ((match = regex.exec(text)) !== null) {
    if (match.index > lastIndex) {
      runs.push(new TextRun({ text: text.slice(lastIndex, match.index) }));
    }
    runs.push(new TextRun({ text: match[1], bold: true }));
    lastIndex = regex.lastIndex;
  }

  if (lastIndex < text.length) {
    runs.push(new TextRun({ text: text.slice(lastIndex) }));
  }

  if (runs.length === 0) {
    runs.push(new TextRun({ text }));
  }

  return runs;
}

function markdownToDocxParagraphs(markdown: string): Paragraph[] {
  const lines = markdown.split("\n");
  const paragraphs: Paragraph[] = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];
    const trimmed = line.trim();

    if (!trimmed) {
      paragraphs.push(new Paragraph({ text: "" }));
      i++;
      continue;
    }

    if (trimmed.startsWith("### ")) {
      paragraphs.push(
        new Paragraph({
          text: trimmed.slice(4),
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 200, after: 80 },
        })
      );
    } else if (trimmed.startsWith("## ")) {
      paragraphs.push(
        new Paragraph({
          text: trimmed.slice(3),
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 280, after: 100 },
        })
      );
    } else if (trimmed.startsWith("# ")) {
      paragraphs.push(
        new Paragraph({
          text: trimmed.slice(2),
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 360, after: 120 },
        })
      );
    } else if (/^-{3,}$/.test(trimmed) || /^_{3,}$/.test(trimmed)) {
      paragraphs.push(
        new Paragraph({
          border: {
            bottom: {
              color: "cccccc",
              space: 1,
              style: BorderStyle.SINGLE,
              size: 6,
            },
          },
          spacing: { before: 160, after: 160 },
          text: "",
        })
      );
    } else if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
      while (
        i < lines.length &&
        (lines[i].trim().startsWith("- ") || lines[i].trim().startsWith("* "))
      ) {
        paragraphs.push(
          new Paragraph({
            children: parseBoldRuns(lines[i].trim().slice(2)),
            bullet: { level: 0 },
            spacing: { before: 40, after: 40 },
          })
        );
        i++;
      }
      continue;
    } else if (/^\d+\.\s/.test(trimmed)) {
      let num = 1;
      while (i < lines.length && /^\d+\.\s/.test(lines[i].trim())) {
        paragraphs.push(
          new Paragraph({
            children: [
              new TextRun(`${num}. `),
              ...parseBoldRuns(lines[i].trim().replace(/^\d+\.\s/, "")),
            ],
            spacing: { before: 40, after: 40 },
          })
        );
        i++;
        num++;
      }
      continue;
    } else {
      paragraphs.push(
        new Paragraph({
          children: parseBoldRuns(trimmed),
          spacing: { before: 0, after: 80 },
        })
      );
    }

    i++;
  }

  return paragraphs;
}

export async function downloadConsentDOCX({
  markdown,
  consentId,
  hospitalName,
  timestamp,
  isResearch = false,
}: {
  markdown: string;
  consentId: string;
  hospitalName: string;
  timestamp: string;
  isResearch?: boolean;
}) {
  const complianceText = isResearch
    ? "Generated by ConsentGen · ICMR Guidelines Compliant · NMC 2023"
    : "Generated by ConsentGen · IMC 2002 Compliant · NMC 2023 · BNS §§24-30";

  const formTitle = isResearch
    ? "INFORMED CONSENT FORM FOR RESEARCH PARTICIPATION"
    : "INFORMED CONSENT FORM";

  const metaTable = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: TableBorders.NONE,
    rows: [
      new TableRow({
        children: [
          new TableCell({
            width: { size: 50, type: WidthType.PERCENTAGE },
            borders: TableBorders.NONE,
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: `Consent ID: ${consentId}`,
                    size: 16,
                    color: "666666",
                  }),
                ],
              }),
            ],
          }),
          new TableCell({
            width: { size: 50, type: WidthType.PERCENTAGE },
            borders: TableBorders.NONE,
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  new TextRun({
                    text: `Date: ${timestamp}`,
                    size: 16,
                    color: "666666",
                  }),
                ],
              }),
            ],
          }),
        ],
      }),
    ],
  });

  const doc = new Document({
    styles: {
      paragraphStyles: [
        {
          id: "Normal",
          name: "Normal",
          basedOn: "Normal",
          run: { font: "Times New Roman", size: 22, color: "222222" },
          paragraph: { spacing: { line: 360 } },
        },
        {
          id: "Heading1",
          name: "Heading 1",
          basedOn: "Normal",
          run: { font: "Times New Roman", size: 26, bold: true, color: "0b0f1a" },
          paragraph: { spacing: { before: 360, after: 120 } },
        },
        {
          id: "Heading2",
          name: "Heading 2",
          basedOn: "Normal",
          run: { font: "Times New Roman", size: 24, bold: true, color: "1a1a2e" },
          paragraph: { spacing: { before: 280, after: 80 } },
        },
        {
          id: "Heading3",
          name: "Heading 3",
          basedOn: "Normal",
          run: { font: "Times New Roman", size: 22, bold: true, color: "333333" },
          paragraph: { spacing: { before: 200, after: 60 } },
        },
      ],
    },
    sections: [
      {
        properties: {
          page: {
            size: { width: 11906, height: 16838 },
            margin: { top: 1134, right: 1134, bottom: 1134, left: 1134 },
          },
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: `${hospitalName || "Medical Institution"}  |  Consent ID: ${consentId}  |  Page `,
                    size: 16,
                    color: "888888",
                  }),
                  new PageNumberElement(),
                ],
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: complianceText,
                    size: 14,
                    color: "aaaaaa",
                  }),
                ],
              }),
            ],
          }),
        },
        children: [
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: formTitle,
                bold: true,
                size: 28,
                color: "0b0f1a",
                font: "Times New Roman",
              }),
            ],
            spacing: { after: 100 },
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: hospitalName || "Medical Institution",
                bold: true,
                size: 24,
                font: "Times New Roman",
                color: "333333",
              }),
            ],
            spacing: { after: 120 },
          }),
          metaTable,
          new Paragraph({
            border: {
              bottom: {
                color: "0b0f1a",
                style: BorderStyle.SINGLE,
                size: 12,
                space: 1,
              },
            },
            spacing: { before: 120, after: 240 },
            text: "",
          }),

          ...markdownToDocxParagraphs(markdown),

          new Paragraph({
            border: {
              bottom: {
                color: "cccccc",
                style: BorderStyle.SINGLE,
                size: 6,
                space: 1,
              },
            },
            spacing: { before: 240, after: 120 },
            text: "",
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: complianceText,
                size: 14,
                color: "aaaaaa",
                font: "Times New Roman",
              }),
            ],
          }),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `consent-${consentId}.docx`;
  a.click();
  URL.revokeObjectURL(url);
}
