type PdfTextRun = { text: string; bold?: boolean };
type PdfContent = object;

function parseBold(text: string): PdfTextRun[] {
  const parts: PdfTextRun[] = [];
  const regex = /\*\*(.*?)\*\*/g;
  let lastIndex = 0;
  let match: RegExpExecArray | null;

  while ((match = regex.exec(text)) !== null) {
    if (match.index > lastIndex) {
      parts.push({ text: text.slice(lastIndex, match.index) });
    }
    parts.push({ text: match[1], bold: true });
    lastIndex = regex.lastIndex;
  }

  if (lastIndex < text.length) {
    parts.push({ text: text.slice(lastIndex) });
  }

  if (parts.length === 0) {
    parts.push({ text });
  }

  return parts;
}

function markdownToPdfContent(markdown: string): PdfContent[] {
  const lines = markdown.split("\n");
  const content: PdfContent[] = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];
    const trimmed = line.trim();

    if (!trimmed) {
      i++;
      continue;
    }

    if (trimmed.startsWith("### ")) {
      content.push({
        text: parseBold(trimmed.slice(4)),
        style: "heading3",
        margin: [0, 10, 0, 4],
      });
    } else if (trimmed.startsWith("## ")) {
      content.push({
        text: parseBold(trimmed.slice(3)),
        style: "heading2",
        margin: [0, 14, 0, 6],
      });
    } else if (trimmed.startsWith("# ")) {
      content.push({
        text: parseBold(trimmed.slice(2)),
        style: "heading1",
        margin: [0, 18, 0, 8],
      });
    } else if (/^-{3,}$/.test(trimmed) || /^_{3,}$/.test(trimmed)) {
      content.push({
        canvas: [
          {
            type: "line",
            x1: 0,
            y1: 0,
            x2: 495,
            y2: 0,
            lineWidth: 0.5,
            lineColor: "#cccccc",
          },
        ],
        margin: [0, 8, 0, 8],
      });
    } else if (/^\d+\.\s/.test(trimmed)) {
      const items: PdfTextRun[][] = [];
      while (i < lines.length && /^\d+\.\s/.test(lines[i].trim())) {
        items.push(parseBold(lines[i].trim().replace(/^\d+\.\s/, "")));
        i++;
      }
      content.push({ ol: items, style: "listItem", margin: [0, 4, 0, 4] });
      continue;
    } else if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
      const items: PdfTextRun[][] = [];
      while (
        i < lines.length &&
        (lines[i].trim().startsWith("- ") || lines[i].trim().startsWith("* "))
      ) {
        items.push(parseBold(lines[i].trim().slice(2)));
        i++;
      }
      content.push({ ul: items, style: "listItem", margin: [0, 4, 0, 4] });
      continue;
    } else {
      content.push({
        text: parseBold(trimmed),
        style: "paragraph",
        margin: [0, 0, 0, 5],
      });
    }

    i++;
  }

  return content;
}

export async function downloadConsentPDF({
  markdown,
  consentId,
  hospitalName,
  timestamp,
  isResearch = false,
}: {
  markdown: string;
  consentId: string;
  hospitalName: string;
  timestamp: string;
  isResearch?: boolean;
}) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const pdfMake = (await import("pdfmake/build/pdfmake" as any)).default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const pdfFonts = (await import("pdfmake/build/vfs_fonts" as any)).default;
  pdfMake.vfs = pdfFonts.vfs ?? pdfFonts.pdfMake?.vfs;

  const complianceText = isResearch
    ? "Generated by ConsentGen · ICMR Guidelines Compliant · NMC 2023"
    : "Generated by ConsentGen · IMC 2002 Compliant · NMC 2023 · BNS §§24-30";

  const formTitle = isResearch
    ? "INFORMED CONSENT FORM FOR RESEARCH PARTICIPATION"
    : "INFORMED CONSENT FORM";

  const docDefinition = {
    pageSize: "A4",
    pageMargins: [50, 72, 50, 56],

    header: (currentPage: number) => ({
      columns: [
        {
          text: hospitalName || "Medical Institution",
          fontSize: 8,
          color: "#555555",
          margin: [50, 20, 0, 0],
          bold: true,
        },
        {
          text: `Consent ID: ${consentId}  |  Page ${currentPage}`,
          alignment: "right",
          fontSize: 8,
          color: "#888888",
          margin: [0, 20, 50, 0],
        },
      ],
    }),

    footer: (currentPage: number, pageCount: number) => ({
      columns: [
        {
          text: complianceText,
          fontSize: 7,
          color: "#aaaaaa",
          margin: [50, 0, 0, 0],
        },
        {
          text: `${currentPage} / ${pageCount}`,
          alignment: "right",
          fontSize: 8,
          color: "#aaaaaa",
          margin: [0, 0, 50, 0],
        },
      ],
    }),

    content: [
      // Document title
      {
        text: formTitle,
        style: "docTitle",
        alignment: "center",
        margin: [0, 0, 0, 6],
      },
      {
        text: hospitalName || "Medical Institution",
        style: "hospitalName",
        alignment: "center",
        margin: [0, 0, 0, 8],
      },
      {
        columns: [
          { text: `Consent ID: ${consentId}`, style: "meta", alignment: "left" },
          { text: `Date: ${timestamp}`, style: "meta", alignment: "right" },
        ],
        margin: [0, 0, 0, 12],
      },
      {
        canvas: [
          {
            type: "line",
            x1: 0,
            y1: 0,
            x2: 495,
            y2: 0,
            lineWidth: 1.5,
            lineColor: "#0b0f1a",
          },
        ],
        margin: [0, 0, 0, 16],
      },

      // AI-generated content
      ...markdownToPdfContent(markdown),

      // Closing line
      {
        canvas: [
          {
            type: "line",
            x1: 0,
            y1: 0,
            x2: 495,
            y2: 0,
            lineWidth: 0.5,
            lineColor: "#cccccc",
          },
        ],
        margin: [0, 16, 0, 8],
      },
      {
        text: complianceText,
        style: "footer",
        alignment: "center",
        margin: [0, 0, 0, 0],
      },
    ],

    styles: {
      docTitle: {
        fontSize: 13,
        bold: true,
        color: "#0b0f1a",
        characterSpacing: 0.5,
      },
      hospitalName: { fontSize: 11, bold: true, color: "#333333" },
      meta: { fontSize: 8, color: "#666666" },
      heading1: { fontSize: 13, bold: true, color: "#0b0f1a" },
      heading2: { fontSize: 11, bold: true, color: "#1a1a2e" },
      heading3: { fontSize: 10, bold: true, color: "#333333" },
      paragraph: { fontSize: 10, color: "#222222", lineHeight: 1.65 },
      listItem: { fontSize: 10, color: "#222222", lineHeight: 1.5 },
      footer: { fontSize: 7, color: "#aaaaaa" },
    },

    defaultStyle: {
      font: "Roboto",
      fontSize: 10,
      lineHeight: 1.5,
    },
  };

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  pdfMake.createPdf(docDefinition as any).download(`consent-${consentId}.pdf`);
}
