export type TemplateCategory =
  | "General Surgery"
  | "Orthopedics"
  | "Cardiology"
  | "Obstetrics & Gynecology"
  | "Gastroenterology"
  | "Neurology & Spine"
  | "Ophthalmology"
  | "ENT"
  | "Urology"
  | "Oncology"
  | "Diagnostics"
  | "Dental"
  | "Psychiatry";

export interface ConsentTemplate {
  id: string;
  category: TemplateCategory;
  title: string;
  description: string;
  procedureName: string;
  consentType: string;
  specificRisks: string;
  alternatives: string;
}

export const PREBUILT_TEMPLATES: ConsentTemplate[] = [
  {
    id: "appendectomy",
    category: "General Surgery",
    title: "Appendectomy",
    description: "Surgical removal of the appendix, typically performed for acute appendicitis.",
    procedureName: "Laparoscopic / Open Appendectomy",
    consentType: "surgical",
    specificRisks: "Bleeding, infection (wound or intra-abdominal abscess), damage to nearby organs (bowel, bladder), conversion from laparoscopic to open surgery, anesthetic complications, incisional hernia.",
    alternatives: "Antibiotic therapy (in selected cases), observation (rarely recommended for acute appendicitis).",
  },
  {
    id: "cholecystectomy",
    category: "General Surgery",
    title: "Laparoscopic Cholecystectomy",
    description: "Removal of the gallbladder, usually for gallstones or inflammation.",
    procedureName: "Laparoscopic Cholecystectomy",
    consentType: "surgical",
    specificRisks: "Bile duct injury requiring reconstructive surgery, bile leak, bleeding, infection, retained gallstones, injury to bowel or blood vessels, conversion to open surgery.",
    alternatives: "Medication to dissolve stones (rarely effective), dietary modification, observation (for asymptomatic stones).",
  },
  {
    id: "hernia_repair",
    category: "General Surgery",
    title: "Inguinal Hernia Repair",
    description: "Surgical repair of a groin hernia, often using synthetic mesh.",
    procedureName: "Inguinal Hernia Repair with Mesh",
    consentType: "surgical",
    specificRisks: "Chronic groin pain, recurrence of the hernia, infection (including mesh infection), bleeding, damage to the spermatic cord or testicle (in males) leading to testicular atrophy, numbness.",
    alternatives: "Observation (watchful waiting) if asymptomatic, truss (supportive garment).",
  },
  {
    id: "knee_replacement",
    category: "Orthopedics",
    title: "Total Knee Replacement",
    description: "Replacement of a damaged knee joint with artificial implants.",
    procedureName: "Total Knee Arthroplasty (TKA)",
    consentType: "surgical",
    specificRisks: "Infection of the joint requiring implant removal, deep vein thrombosis (DVT) or pulmonary embolism (PE), stiffness, nerve or blood vessel damage, implant wear or loosening over time.",
    alternatives: "Physical therapy, weight loss, NSAIDs, corticosteroid or hyaluronic acid injections, knee bracing.",
  },
  {
    id: "hip_replacement",
    category: "Orthopedics",
    title: "Total Hip Replacement",
    description: "Replacement of a damaged hip joint with a prosthetic implant.",
    procedureName: "Total Hip Arthroplasty (THA)",
    consentType: "surgical",
    specificRisks: "Hip dislocation, leg length discrepancy, infection, deep vein thrombosis (DVT), nerve injury (sciatic nerve), implant loosening, fracture during surgery.",
    alternatives: "Pain medication, physical therapy, walking aids, weight loss.",
  },
  {
    id: "arthroscopy_knee",
    category: "Orthopedics",
    title: "Knee Arthroscopy",
    description: "Minimally invasive procedure to diagnose and treat knee joint problems.",
    procedureName: "Diagnostic/Therapeutic Knee Arthroscopy",
    consentType: "surgical",
    specificRisks: "Bleeding into the joint (hemarthrosis), infection, blood clots, stiffness, failure to relieve symptoms, cartilage damage.",
    alternatives: "Conservative management (rest, ice, physical therapy, injections).",
  },
  {
    id: "cabg",
    category: "Cardiology",
    title: "Coronary Artery Bypass Grafting (CABG)",
    description: "Open-heart surgery to bypass blocked coronary arteries.",
    procedureName: "Coronary Artery Bypass Grafting (CABG)",
    consentType: "surgical",
    specificRisks: "Myocardial infarction (heart attack) during or after surgery, stroke, bleeding requiring transfusion, sternal wound infection, arrhythmias (e.g., atrial fibrillation), death.",
    alternatives: "Percutaneous coronary intervention (Angioplasty/Stenting), optimal medical therapy.",
  },
  {
    id: "angioplasty",
    category: "Cardiology",
    title: "Angioplasty & Stenting",
    description: "Procedure to open clogged heart arteries using a balloon and stent.",
    procedureName: "Percutaneous Coronary Intervention (PCI) with Stent",
    consentType: "minor_procedure",
    specificRisks: "Bleeding or hematoma at the puncture site (groin or wrist), damage to the blood vessel, allergic reaction to contrast dye, kidney injury from dye, arrhythmias, heart attack, stroke.",
    alternatives: "Medical management, Coronary Artery Bypass Grafting (CABG).",
  },
  {
    id: "pacemaker",
    category: "Cardiology",
    title: "Pacemaker Insertion",
    description: "Implantation of a device to regulate the heartbeat.",
    procedureName: "Permanent Pacemaker Implantation",
    consentType: "minor_procedure",
    specificRisks: "Pneumothorax (collapsed lung), lead dislodgement, infection of the pocket or leads, bleeding, cardiac perforation, device malfunction.",
    alternatives: "Medication (limited efficacy for certain bradycardias), temporary pacing.",
  },
  {
    id: "c_section",
    category: "Obstetrics & Gynecology",
    title: "Cesarean Section (C-Section)",
    description: "Surgical delivery of a baby through incisions in the abdomen and uterus.",
    procedureName: "Lower Segment Cesarean Section (LSCS)",
    consentType: "obstetric",
    specificRisks: "Heavy bleeding requiring transfusion or hysterectomy, infection (endometritis, wound), injury to bladder or bowel, blood clots (DVT/PE), respiratory issues for the baby, risks in future pregnancies (placenta accreta, uterine rupture).",
    alternatives: "Vaginal delivery, instrumental vaginal delivery (forceps/vacuum) if appropriate.",
  },
  {
    id: "hysterectomy",
    category: "Obstetrics & Gynecology",
    title: "Total Hysterectomy",
    description: "Surgical removal of the uterus.",
    procedureName: "Total Abdominal/Laparoscopic Hysterectomy",
    consentType: "surgical",
    specificRisks: "Bleeding, infection, injury to the ureters, bladder, or bowel, early menopause (if ovaries are removed), pelvic organ prolapse later in life, deep vein thrombosis.",
    alternatives: "Hormonal therapy, endometrial ablation, uterine artery embolization, myomectomy.",
  },
  {
    id: "colonoscopy",
    category: "Gastroenterology",
    title: "Colonoscopy",
    description: "Endoscopic examination of the large bowel and distal part of the small bowel.",
    procedureName: "Diagnostic and Therapeutic Colonoscopy",
    consentType: "diagnostic",
    specificRisks: "Bowel perforation requiring emergency surgery, bleeding (especially if polyps are removed), adverse reaction to sedation, missed lesions or polyps.",
    alternatives: "CT colonography, barium enema, stool tests (FIT/FOBT).",
  },
  {
    id: "endoscopy",
    category: "Gastroenterology",
    title: "Upper GI Endoscopy (OGD)",
    description: "Visual examination of the esophagus, stomach, and duodenum.",
    procedureName: "Esophagogastroduodenoscopy (EGD / OGD)",
    consentType: "diagnostic",
    specificRisks: "Sore throat, bleeding from biopsy sites, perforation of the esophagus or stomach, aspiration pneumonia, adverse reaction to sedation.",
    alternatives: "Barium swallow, CT scan, empirical medical treatment.",
  },
  {
    id: "cataract",
    category: "Ophthalmology",
    title: "Cataract Surgery",
    description: "Removal of the cloudy lens of the eye and replacement with an artificial lens.",
    procedureName: "Phacoemulsification with Intraocular Lens (IOL) Implantation",
    consentType: "minor_procedure",
    specificRisks: "Endophthalmitis (severe eye infection leading to vision loss), posterior capsule rupture, retinal detachment, glaucoma, corneal swelling, need for glasses post-surgery.",
    alternatives: "Observation, updating prescription glasses (temporary solution).",
  },
  {
    id: "lasik",
    category: "Ophthalmology",
    title: "LASIK Eye Surgery",
    description: "Laser refractive surgery to correct myopia, hyperopia, and astigmatism.",
    procedureName: "LASIK (Laser-Assisted In Situ Keratomileusis)",
    consentType: "minor_procedure",
    specificRisks: "Dry eyes, glare, halos, double vision, undercorrections or overcorrections, flap complications, infection, vision loss.",
    alternatives: "Eyeglasses, contact lenses, PRK (Photorefractive keratectomy).",
  },
  {
    id: "tonsillectomy",
    category: "ENT",
    title: "Tonsillectomy",
    description: "Surgical removal of the tonsils.",
    procedureName: "Tonsillectomy",
    consentType: "surgical",
    specificRisks: "Primary or secondary hemorrhage (bleeding) requiring return to the operating room, severe throat pain, dehydration, infection, voice changes, anesthetic risks.",
    alternatives: "Antibiotics (for recurrent infections), observation.",
  },
  {
    id: "fess",
    category: "ENT",
    title: "Sinus Surgery (FESS)",
    description: "Endoscopic surgery to open sinus passages.",
    procedureName: "Functional Endoscopic Sinus Surgery (FESS)",
    consentType: "surgical",
    specificRisks: "Bleeding, infection, cerebrospinal fluid (CSF) leak, injury to the eye or optic nerve (leading to vision changes), loss of smell.",
    alternatives: "Nasal corticosteroids, saline irrigations, systemic antibiotics/steroids.",
  },
  {
    id: "lumbar_puncture",
    category: "Neurology & Spine",
    title: "Lumbar Puncture (Spinal Tap)",
    description: "Needle inserted into the spinal canal to collect cerebrospinal fluid.",
    procedureName: "Lumbar Puncture",
    consentType: "diagnostic",
    specificRisks: "Post-dural puncture headache, back pain, bleeding (epidural hematoma), infection (meningitis), nerve root irritation, brain herniation (rare, if elevated intracranial pressure).",
    alternatives: "CT/MRI brain (provides different information), empirical treatment.",
  },
  {
    id: "spinal_fusion",
    category: "Neurology & Spine",
    title: "Spinal Fusion",
    description: "Surgery to permanently connect two or more vertebrae in your spine.",
    procedureName: "Spinal Fusion with Instrumentation",
    consentType: "surgical",
    specificRisks: "Nerve damage causing weakness or paralysis, dural tear (CSF leak), failure of bone fusion (pseudoarthrosis), implant failure or migration, infection, bleeding.",
    alternatives: "Physical therapy, pain management, epidural steroid injections, decompression without fusion.",
  },
  {
    id: "prostate_biopsy",
    category: "Urology",
    title: "Prostate Biopsy",
    description: "Removal of small samples of prostate tissue for examination.",
    procedureName: "Transrectal / Transperineal Ultrasound-Guided Prostate Biopsy",
    consentType: "diagnostic",
    specificRisks: "Blood in urine, stool, or semen, severe infection (sepsis) requiring hospitalization, acute urinary retention, pain.",
    alternatives: "PSA monitoring, MRI of the prostate, observation.",
  },
  {
    id: "chemotherapy",
    category: "Oncology",
    title: "Chemotherapy Administration",
    description: "Systemic treatment using chemical substances to kill cancer cells.",
    procedureName: "Intravenous Chemotherapy",
    consentType: "minor_procedure",
    specificRisks: "Nausea, vomiting, hair loss, immunosuppression (increased risk of severe infection), anemia, bleeding, organ toxicity (heart, liver, kidneys), allergic reaction.",
    alternatives: "Radiation therapy, targeted therapy, immunotherapy, palliative care without active treatment.",
  },
  {
    id: "mri_contrast",
    category: "Diagnostics",
    title: "MRI with Contrast",
    description: "Magnetic Resonance Imaging with intravenous gadolinium contrast.",
    procedureName: "MRI with IV Contrast",
    consentType: "diagnostic",
    specificRisks: "Allergic reaction to contrast media, nephrogenic systemic fibrosis (in patients with severe kidney disease), retention of gadolinium in the body, discomfort from claustrophobia.",
    alternatives: "MRI without contrast, CT scan, Ultrasound.",
  },
  {
    id: "blood_transfusion",
    category: "General Surgery",
    title: "Blood Transfusion",
    description: "Intravenous administration of whole blood or blood components.",
    procedureName: "Blood / Blood Product Transfusion",
    consentType: "blood_transfusion",
    specificRisks: "Allergic reaction, fever, hemolytic transfusion reaction (mismatched blood), transmission of infectious diseases (HIV, Hepatitis B/C), fluid overload (TACO), acute lung injury (TRALI).",
    alternatives: "Iron or vitamin B12 supplementation, Erythropoietin (EPO), autologous blood donation, volume expanders (saline).",
  },
  {
    id: "ect",
    category: "Psychiatry",
    title: "Electroconvulsive Therapy (ECT)",
    description: "Brief electrical stimulation of the brain while the patient is under anesthesia.",
    procedureName: "Electroconvulsive Therapy (ECT)",
    consentType: "psychiatric",
    specificRisks: "Memory loss (retrograde and anterograde amnesia), confusion, headache, muscle soreness, cardiovascular changes (arrhythmias, hypertension) during the procedure, anesthetic risks.",
    alternatives: "Pharmacotherapy (antidepressants, antipsychotics), psychotherapy, Transcranial Magnetic Stimulation (TMS).",
  },
  {
    id: "dental_extraction",
    category: "Dental",
    title: "Tooth Extraction / Wisdom Tooth Removal",
    description: "Surgical removal of a tooth from its socket in the bone.",
    procedureName: "Surgical / Simple Tooth Extraction",
    consentType: "minor_procedure",
    specificRisks: "Dry socket (alveolar osteitis), infection, bleeding, name or tooth location errors, nerve injury leading to numbness of lip/tongue/chin (temporary or permanent), sinus communication (for upper teeth).",
    alternatives: "Root canal therapy (if restorable), observation (for asymptomatic impacted wisdom teeth).",
  }
];

export type ResearchCategory =
  | "Clinical Trial"
  | "Observational Study"
  | "Survey & Questionnaire"
  | "Academic Research";

export interface ResearchTemplate {
  id: string;
  type: "research";
  category: ResearchCategory;
  title: string;
  description: string;
  studyTitle: string;
  principalInvestigator: string;
  department: string;
  institutionName: string;
  institutionAddress: string;
  contactMobile: string;
  studyPurpose: string;
  dataToCollect: string;
  timeRequired: string;
  risks: string;
  benefits: string;
  monetaryBenefits: string;
}

export const RESEARCH_TEMPLATES: ResearchTemplate[] = [
  {
    id: "aetcom_study",
    type: "research",
    category: "Survey & Questionnaire",
    title: "AETCOM Module 1.2 Study",
    description: "Evaluates medical students' perception of using role play for ethics and communication modules.",
    studyTitle: "Perception on Role Play as a Teaching-Learning Method for AETCOM Module [1.2] among First-Year Medical Students — A Descriptive Cross-Sectional Study",
    principalInvestigator: "Dr. Mohammed Aslam",
    department: "Department of Physiology",
    institutionName: "S R Patil Medical College Hospital and Research Center",
    institutionAddress: "Badagandi, Bagalkote, Karnataka, India",
    contactMobile: "8310363634",
    studyPurpose: "To assess the perception, usefulness, and effectiveness of role play as a teaching-learning method for the AETCOM Module 1.2 (attitude, ethics, and communication skills) among first-year medical students.",
    dataToCollect: "Completion of a questionnaire detailing student experience, involvement, and learning during the role play session.",
    timeRequired: "10-15 minutes",
    risks: "There are no physical, mental, or emotional risks involved in this study. It is simply a reflection of your learning experience.",
    benefits: "No direct benefit to the participant. However, your feedback may help improve the way AETCOM modules are taught to future medical students.",
    monetaryBenefits: "No monetary benefits or compensation are provided for participating in this research study.",
  },
  {
    id: "ssi_surveillance",
    type: "research",
    category: "Observational Study",
    title: "Surgical Site Infection (SSI) Surveillance",
    description: "Surveillance registry tracking wound infection rates and outcomes after major surgeries.",
    studyTitle: "Surgical Site Infection (SSI) Surveillance and Outcomes Monitoring Registry",
    principalInvestigator: "Dr. S. R. Patil",
    department: "Department of Surgery",
    institutionName: "S R Patil Medical College, Hospital & Research Centre",
    institutionAddress: "Badagandi, Bagalkote, Karnataka, India",
    contactMobile: "8310363634",
    studyPurpose: "To conduct research on Surgical Site Infection (SSI) Surveillance to monitor infection rates, improve surgical care, and prevent future infections.",
    dataToCollect: "Collection of medical information from patient surgical records, wound clinical data, and follow-up records for surveillance purposes only.",
    timeRequired: "Retrospective record review (no direct participant time required)",
    risks: "There are no physical or medical risks. All data will be anonymized to protect participant identity and confidentiality.",
    benefits: "No direct benefit to the participant. However, data helps monitor and reduce surgical site infection rates and improve surgical care outcomes.",
    monetaryBenefits: "No monetary benefits or compensation are provided for participation.",
  },
  {
    id: "covid_vaccine_trial",
    type: "research",
    category: "Clinical Trial",
    title: "Phase III COVID-19 Booster Vaccine Trial",
    description: "Evaluating safety, tolerability, and immunogenicity of a new recombinant vaccine formulation.",
    studyTitle: "A Randomized, Double-Blind, Phase III Clinical Trial to Evaluate the Efficacy and Safety of Recombinant COVID-19 Booster Vaccine in Healthy Adults",
    principalInvestigator: "Dr. Rajesh K. Mehta",
    department: "Department of Medicine",
    institutionName: "City General Hospital & Medical College",
    institutionAddress: "45 Health Sciences Ave, Sector 12, New Delhi",
    contactMobile: "9812345678",
    studyPurpose: "To evaluate the safety, protective efficacy, and immunogenicity of the candidate recombinant booster vaccine compared to current approved boosters in healthy adult participants.",
    dataToCollect: "Intramuscular vaccine/placebo administration, blood samples at regular intervals (day 0, 14, 28, 180), and daily symptom logging through a mobile app.",
    timeRequired: "6 visits over 6 months (total duration of approximately 10 hours)",
    risks: "Common vaccine side effects (mild fever, soreness at injection site, fatigue, muscle aches). Extremely rare risk of allergic reactions or anaphylaxis.",
    benefits: "Potential active immunization protection against SARS-CoV-2 variants. Free clinical assessments and blood tests.",
    monetaryBenefits: "Travel allowance and reimbursement for time spent at clinical trial visits (Rs. 1,000 per visit).",
  },
  {
    id: "hypertension_efficacy_trial",
    type: "research",
    category: "Clinical Trial",
    title: "Hypertension Combination Therapy Trial",
    description: "Investigating dual-action combination tablets vs monotherapy for resistant hypertension.",
    studyTitle: "Evaluation of Resistant Hypertension Control Using Low-Dose Dual Combination Therapy vs High-Dose Monotherapy: A Randomized Trial",
    principalInvestigator: "Dr. Ananya Sharma",
    department: "Department of Cardiology",
    institutionName: "National Institute of Cardiovascular Sciences",
    institutionAddress: "Okhla Road, New Delhi, India",
    contactMobile: "9988776655",
    studyPurpose: "To determine if combination therapy achieves target blood pressure control faster and with fewer adverse events than single-agent uptitration in patients with resistant hypertension.",
    dataToCollect: "Blood pressure measurements, medication diaries, standard electrocardiogram (ECG), kidney function blood panels, and adverse event reports.",
    timeRequired: "4 follow-up clinic visits over 12 weeks",
    risks: "Potential side effects of anti-hypertensive drugs (dizziness, fatigue, mild headache, hypotension, or electrolyte imbalances).",
    benefits: "Access to specialist cardiology evaluations and closer monitoring of hypertensive condition, with potentially improved blood pressure control.",
    monetaryBenefits: "Standard clinical evaluation and all study medications provided free of cost.",
  },
  {
    id: "diabetic_nephropathy_cohort",
    type: "research",
    category: "Observational Study",
    title: "Diabetic Nephropathy Registry",
    description: "Longitudinal tracking of biomarker patterns correlating with progression of kidney damage in diabetics.",
    studyTitle: "Longitudinal Cohort Study on Biomarkers for Early Progression Identification in Diabetic Nephropathy",
    principalInvestigator: "Dr. Vikas Gowda",
    department: "Department of Nephrology",
    institutionName: "Victoria Hospital & Bangalore Medical College",
    institutionAddress: "K.R. Road, Bengaluru, Karnataka",
    contactMobile: "9448012345",
    studyPurpose: "To identify novel serum and urinary biomarkers that predict rapid renal decline in patients with type 2 diabetes mellitus.",
    dataToCollect: "Annual clinical examination data, urine samples (microalbuminuria screening), blood samples (GFR levels), and medical history records.",
    timeRequired: "One annual clinic visit (approx. 45 mins) over 3 years",
    risks: "Minimal risk associated with standard venipuncture (temporary bruising, mild pain at blood draw site).",
    benefits: "Comprehensive annual renal screening results shared with your primary care physician at no charge.",
    monetaryBenefits: "No compensation provided. Diagnostic screenings are fully sponsored by the study grant.",
  },
  {
    id: "pediatric_asthma_usability",
    type: "research",
    category: "Clinical Trial",
    title: "Pediatric Inhaler Usability Study",
    description: "Assessing inhalation technique and compliance with a new pediatric spacer device.",
    studyTitle: "Usability, Technique Correctness, and Parental Preference for Spacer Devices in Asthmatic Children Aged 4-8 Years",
    principalInvestigator: "Dr. Priya Deshmukh",
    department: "Department of Pediatrics",
    institutionName: "KEM Hospital and Medical College",
    institutionAddress: "Acharya Donde Marg, Parel, Mumbai",
    contactMobile: "9820011223",
    studyPurpose: "To assess spacer inhalation technique correctness and treatment compliance among young children utilizing a new ergonomic spacer device compared to traditional devices.",
    dataToCollect: "Visual technique assessments by pediatric nurses, feedback questionnaires from parents, and compliance diaries.",
    timeRequired: "2 outpatient evaluation visits (30 minutes each)",
    risks: "No physical risks. Standard inhalation therapy is continued as prescribed by the child's regular pediatrician.",
    benefits: "Detailed counseling on correct inhaler usage techniques which can lead to better asthma control for the child.",
    monetaryBenefits: "Complementary spacer device provided to the child for home use.",
  },
  {
    id: "cancer_genomics_biobank",
    type: "research",
    category: "Academic Research",
    title: "Breast Cancer Genomics & Biobank Study",
    description: "Tissue and blood specimen banking for genetic mutation mapping in breast cancer patients.",
    studyTitle: "Indian Breast Cancer Genome Atlas: Establishment of a Genomics Registry and Biospecimen Bank",
    principalInvestigator: "Dr. S. Vishwanathan",
    department: "Department of Oncopathology",
    institutionName: "Tata Memorial Centre",
    institutionAddress: "Dr. Ernest Borges Road, Parel, Mumbai, Maharashtra",
    contactMobile: "9004001122",
    studyPurpose: "To identify specific genetic mutations and biomarkers common in the Indian population to improve targeted therapies for breast cancer.",
    dataToCollect: "Surgically resected tumor tissue samples (collected post-biopsy/surgery), a single 10ml blood sample, and longitudinal clinical outcomes data.",
    timeRequired: "10 minutes for blood collection (tissue collection happens during standard surgical procedure)",
    risks: "Standard blood draw risks (slight discomfort, bruising). No additional surgical risks as tissue is taken from specimens already scheduled for removal.",
    benefits: "No direct treatment benefit. Contributions help build national cancer genomic databases to guide future targeted therapies.",
    monetaryBenefits: "No monetary compensation. Diagnostic mutation reports will be shared with the patient's oncologist.",
  },
  {
    id: "cardiovascular_risk_survey",
    type: "research",
    category: "Survey & Questionnaire",
    title: "Cardiovascular Risk Factors Survey",
    description: "Community survey evaluating lifestyle, dietary habits, and early signs of cardiovascular disease.",
    studyTitle: "Epidemiological Survey on Cardiovascular Risk Factors and Lifestyle Correlates in Semi-Urban Communities",
    principalInvestigator: "Dr. G. S. Murthy",
    department: "Department of Community Medicine",
    institutionName: "S R Patil Medical College Hospital and Research Center",
    institutionAddress: "Badagandi, Bagalkote, Karnataka, India",
    contactMobile: "8310363634",
    studyPurpose: "To estimate the prevalence of hypertension, hyperlipidemia, and diabetic risk profiles in semi-urban adult populations and analyze lifestyle correlations.",
    dataToCollect: "Answers to a questionnaire regarding physical activity, smoking, diet, along with baseline measurements of blood pressure, height, weight, and a finger-prick blood glucose test.",
    timeRequired: "20-30 minutes for survey and measurements",
    risks: "Minimal discomfort from blood pressure cuff and a brief pinprick sensation from the finger-stick test.",
    benefits: "Immediate feedback on blood pressure, body mass index (BMI), and blood glucose levels with counseling on cardiovascular health.",
    monetaryBenefits: "Free health report card and health counseling provided at the end of the survey.",
  },
  {
    id: "sleep_apnea_cognition",
    type: "research",
    category: "Observational Study",
    title: "Sleep Apnea & Cognitive Decline Study",
    description: "Investigating the link between obstructive sleep apnea severity and cognitive decline in seniors.",
    studyTitle: "Cognitive Performance Correlates in Elderly Patients Diagnosed with Severe Obstructive Sleep Apnea",
    principalInvestigator: "Dr. Suresh Ramachandran",
    department: "Department of Neurology",
    institutionName: "Madras Medical College & General Hospital",
    institutionAddress: "E.V.R. Salai, Park Town, Chennai, Tamil Nadu",
    contactMobile: "9840123456",
    studyPurpose: "To evaluate if the severity of hypoxia in obstructive sleep apnea (OSA) is associated with accelerated cognitive decline or early signs of dementia in elderly patients.",
    dataToCollect: "Polysomnography sleep study metrics, cognitive test responses (MMSE panel), and brain magnetic resonance imaging (MRI) scan reports.",
    timeRequired: "1 overnight sleep study and 1 cognitive test session (approx. 1 hour)",
    risks: "No physical risks. Sleep studies are non-invasive. MRI scans involve loud noises and lying still inside the scanner.",
    benefits: "Detailed clinical sleep study report indicating sleep architecture and apnea severity, which helps direct treatment.",
    monetaryBenefits: "Study covers the full cost of the diagnostic sleep study and cognitive evaluations.",
  },
  {
    id: "telemedicine_geriatric_survey",
    type: "research",
    category: "Survey & Questionnaire",
    title: "Geriatric Telemedicine Usability Survey",
    description: "Evaluating satisfaction and barriers in utilizing telemedicine platforms among elderly patients.",
    studyTitle: "Geriatric Patient Perspectives on Telemedicine Barriers, Usability, and Satisfaction in Primary Care",
    principalInvestigator: "Dr. Meera Iyer",
    department: "Department of Family Medicine",
    institutionName: "S R Patil Medical College Hospital and Research Center",
    institutionAddress: "Badagandi, Bagalkote, Karnataka, India",
    contactMobile: "8310363634",
    studyPurpose: "To study usability barriers, ease of access, and general patient satisfaction among elderly patients utilizing virtual video consultations for primary health care.",
    dataToCollect: "Answering an interviewer-led questionnaire regarding access to technology, call quality, clarity of doctor instructions, and preference.",
    timeRequired: "15 minutes, conducted over telephone or post-consultation",
    risks: "No physical, mental, or emotional risks. Participation does not affect current or future telemedicine access.",
    benefits: "No direct benefit. Results help improve the hospital's virtual consultation software interface for senior citizens.",
    monetaryBenefits: "No monetary benefits are provided for participating in this survey.",
  },
  {
    id: "arthritis_lifestyle_trial",
    type: "research",
    category: "Clinical Trial",
    title: "Rheumatoid Arthritis Lifestyle Trial",
    description: "Evaluating impact of a structured anti-inflammatory diet and exercise program alongside pharmacotherapy.",
    studyTitle: "Adjunctive Anti-Inflammatory Diet and Yoga Intervention in Patients with Active Rheumatoid Arthritis",
    principalInvestigator: "Dr. Sandeep Kulkarni",
    department: "Department of Rheumatology",
    institutionName: "King George Medical University (KGMU)",
    institutionAddress: "Chowk, Lucknow, Uttar Pradesh",
    contactMobile: "9415011223",
    studyPurpose: "To evaluate the efficacy of a structured anti-inflammatory dietary regimen and daily yoga sessions in reducing joint pain and inflammatory markers (CRP, ESR) in rheumatoid arthritis patients.",
    dataToCollect: "Dietary tracking logs, daily exercise checklists, joint pain assessment forms, and monthly blood draws for inflammatory markers.",
    timeRequired: "12 weeks program with monthly clinic assessments",
    risks: "Minimal risk of minor muscle strain during yoga. No changes are made to standard prescribed medications.",
    benefits: "Potential reduction in joint pain, stiffness, and reliance on rescue pain medications, with free dietary coaching.",
    monetaryBenefits: "All monthly blood tests and yoga training sessions are fully funded by the research team.",
  },
  {
    id: "medical_student_burnout",
    type: "research",
    category: "Survey & Questionnaire",
    title: "Medical Student Burnout Assessment",
    description: "Evaluating burnout levels and coping strategies among medical students during exam periods.",
    studyTitle: "Prevalence of Academic Burnout and Coping Mechanisms among Undergraduate Medical Students",
    principalInvestigator: "Dr. Mohammed Aslam",
    department: "Department of Physiology",
    institutionName: "S R Patil Medical College Hospital and Research Center",
    institutionAddress: "Badagandi, Bagalkote, Karnataka, India",
    contactMobile: "8310363634",
    studyPurpose: "To evaluate stress levels, academic burnout indicators, and the efficacy of different mental health coping mechanisms among MBBS students.",
    dataToCollect: "Completion of an anonymous online survey detailing academic stress levels, sleep hygiene, and emotional well-being.",
    timeRequired: "10 minutes",
    risks: "No physical risks. A slight emotional response may occur when reflecting on personal stress levels.",
    benefits: "No direct benefit. Aggregated findings help design student wellness programs and stress-relief workshops at the college.",
    monetaryBenefits: "Participation is completely voluntary with no financial incentive.",
  },
  {
    id: "icu_microbiome_mapping",
    type: "research",
    category: "Academic Research",
    title: "ICU Patient Microbiome Mapping Study",
    description: "Mapping microbiome changes in critically ill patients to track multi-drug resistant colonization.",
    studyTitle: "Metagenomic Characterization of Gut Microbiome Alterations and Resistance Profiles in Intensive Care Unit Patients",
    principalInvestigator: "Dr. Nivedita Rao",
    department: "Department of Microbiology",
    institutionName: "Postgraduate Institute of Medical Education & Research (PGIMER)",
    institutionAddress: "Sector 12, Chandigarh, India",
    contactMobile: "9876001122",
    studyPurpose: "To track gut microbiome changes in ICU patients during broad-spectrum antibiotic therapy and identify early indicators of colonization by superbugs.",
    dataToCollect: "Fecal swab collections at ICU admission, day 3, day 7, and clinical charts monitoring antibiotic drug administration.",
    timeRequired: "Less than 5 minutes for swabs (performed by trained clinical staff during ICU care)",
    risks: "No physical risk. Swab collections are non-invasive and performed safely in the ICU.",
    benefits: "No direct treatment benefit. Results help develop better infection control protocols in critical care units.",
    monetaryBenefits: "No compensation provided. Metagenomic testing costs are fully covered.",
  },
  {
    id: "chronic_pain_mindfulness",
    type: "research",
    category: "Clinical Trial",
    title: "Chronic Pain Mindfulness Therapy Trial",
    description: "Testing a virtual reality mindfulness program for pain intensity management in lower back pain patients.",
    studyTitle: "Efficacy of Virtual Reality Guided Mindfulness Meditation for Pain Mitigation in Chronic Lower Back Pain",
    principalInvestigator: "Dr. Rohan Bakshi",
    department: "Department of Physical Medicine & Rehabilitation",
    institutionName: "All India Institute of Medical Sciences (AIIMS)",
    institutionAddress: "Ansari Nagar, New Delhi",
    contactMobile: "9810998877",
    studyPurpose: "To compare virtual reality (VR) guided mindfulness meditation sessions with standard physiotherapy for reducing subjective pain ratings in chronic lower back pain sufferers.",
    dataToCollect: "Subjective pain score tracking (Visual Analog Scale), wearable device sleep metrics, and post-session feedback forms.",
    timeRequired: "20-minute daily VR sessions at home for 4 weeks",
    risks: "Minor risk of mild dizziness or motion sickness from the virtual reality headset.",
    benefits: "Access to free virtual reality equipment during the trial, with potential improvements in chronic back pain management.",
    monetaryBenefits: "A VR headset is loaned to the participant for the duration of the study at no cost.",
  },
  {
    id: "neonatal_hearing_registry",
    type: "research",
    category: "Observational Study",
    title: "Neonatal Hearing Screening Registry",
    description: "Tracking compliance and early intervention outcomes for congenital hearing loss in newborns.",
    studyTitle: "Implementation Registry and Early Intervention Outcomes for Universal Neonatal Hearing Screenings",
    principalInvestigator: "Dr. Susan Mathew",
    department: "Department of Neonatology",
    institutionName: "St. John's Medical College Hospital",
    institutionAddress: "Sarjapur Road, Bengaluru, Karnataka",
    contactMobile: "9845098765",
    studyPurpose: "To evaluate the compliance rates, follow-up rates, and early speech-language intervention success metrics of newborns screened with automated auditory brainstem response testing.",
    dataToCollect: "Neonatal diagnostic hearing test results, follow-up clinic records, and pediatric milestone surveys at 6 and 12 months.",
    timeRequired: " milestoning questionnaires completed by parents (10 mins each)",
    risks: "No physical risks. Hearing testing is non-invasive and routinely performed while the infant is sleeping.",
    benefits: "Early detection and intervention support for congenital hearing loss, maximizing speech-language developmental success.",
    monetaryBenefits: "No financial compensation. Post-discharge hearing evaluations are provided at a subsidized rate.",
  },
  {
    id: "ibd_dietary_questionnaire",
    type: "research",
    category: "Survey & Questionnaire",
    title: "Inflammatory Bowel Disease Diet Study",
    description: "Survey investigating dietary triggers and nutritional deficiencies in patients with Crohn's and Colitis.",
    studyTitle: "Patient-Reported Dietary Triggers and Nutritional Status in Patients with Inflammatory Bowel Disease",
    principalInvestigator: "Dr. Alok Sen",
    department: "Department of Gastroenterology",
    institutionName: "S R Patil Medical College Hospital and Research Center",
    institutionAddress: "Badagandi, Bagalkote, Karnataka, India",
    contactMobile: "8310363634",
    studyPurpose: "To study common self-reported dietary triggers and nutritional patterns that correlate with disease flares in patients diagnosed with Crohn's disease or Ulcerative Colitis.",
    dataToCollect: "Completion of a detailed food frequency questionnaire, symptom flare logging, and standard clinic nutrition metrics.",
    timeRequired: "15-20 minutes to complete the questionnaire",
    risks: "No physical, mental, or emotional risks. Patient information remains completely confidential.",
    benefits: "Provides a personalized analysis of self-reported trigger foods that patients can review with their gastroenterologist.",
    monetaryBenefits: "No monetary benefits are provided for participating.",
  }
];
